Adopt strict policy for koji submissions
Because there have been very few situations in the past requiring a
"make koji" from a branch other than master, add a strict check that the
active local branch is "master". This also blocks submissions from a
"detached" state, which was previously permitted.

Also, fix and consolidate the git push commands into one. Now that the
branch check is implemented, the "master" refspec can be used, and
explicitly push *one* tag (the tag created immediately before the push).
The --follow-tags and --tags options don't have the intended effect, so
omit them.

Signed-off-by: Patrick McCarty <patrick.mccarty@intel.com>

diff --git a/Makefile.common b/Makefile.common
--- a/Makefile.common
+++ b/Makefile.common
@@ -238,10 +238,13 @@ prekoji-checks:
 koji: prekoji-checks kojidef
 	@$(MAKE) spdxcheck
 	@$(MAKE) checkblacklist
+	@if ! git branch | grep -q -E '^\* master'; then \
+		echo "Error: Must be on the master branch to submit to koji" >&2; \
+		exit 1; \
+	fi
 	git pull --rebase
 	git tag $(SRPMVERS)
-	git push --follow-tags
-	git push --tags
+	git push origin master refs/tags/$(SRPMVERS)
 	$(KOJI_CMD) build $$KOJI_NOWAIT $(KOJI_TAG) $(PKG_BASE_URL)/$(PKG_NAME)?#$(SRPMVERS)
 
 #help rekoji: In case a previous 'make koji' failed, trigger a rebuild for the
