sources/generateupstream: properly handle curl errors
If any of the curl commands fail, it's better for the entire target to
fail. In this way, developers will be properly notified.

Signed-off-by: Patrick McCarty <patrick.mccarty@intel.com>

diff --git a/Makefile.common b/Makefile.common
--- a/Makefile.common
+++ b/Makefile.common
@@ -221,7 +221,10 @@ ifneq ($(strip $(SOURCES_URL)),)
 			*://*) n="$$u" ;; \
 			*)     n="$(SOURCES_URL)/$$u" ;; \
 		esac; \
-		curl --fail -L "$$n" -o `basename "$$n"`; \
+		if ! curl --fail -L "$$n" -o `basename "$$n"`; then \
+			echo "Failed to download $$n"; \
+			exit 1; \
+		fi; \
 	done < upstream
 else
 	@tmp=$$(mktemp -d -p "."); \
@@ -370,7 +373,10 @@ generateupstream:
 	for url in $$urls; do \
 		filename=$$(basename $$url); \
 		if [ ! -e $$filename ]; then \
-			curl --fail -L -O $$url; \
+			if ! curl --fail -L -O $$url; then \
+				echo "Failed to download $$url"; \
+				exit 1; \
+			fi; \
 		fi; \
 		echo $$(sha1sum $$filename | cut -d\  -f1)/$$filename >> upstream; \
 	done
